[ores]

[ores.fe]
name = "Iron"
description = "A strong, hard magnetic silvery-gray metal, often used in construction and manufacturing."
color = "#B0B0B0"
value = 1

[ores.ce]
name = "Cerium"
description = "A soft, silvery, ductile metal that oxidizes in air, used in various chemical and metallurgical applications."
color = "#FFFFFF"
value = 2

[ores.la]
name = "Lanthanum"
description = "A soft, malleable, silvery-white metal, used in various alloys and as a catalyst in some chemical reactions."
color = "#FFFFFF"
value = 3

[ores.ni]
name = "Nickel"
description = "A hard, silvery-white metal with a high melting point, used in alloys and for plating other metals."
color = "#A3A3A3"
value = 4

[ores.nd]
name = "Neodymium"
description = "A silvery-white metal that is used in magnets, lasers, and various high-tech applications."
color = "#C2C2C2"
value = 5

[ores.co]
name = "Cobalt"
description = "A hard, lustrous, gray metal used in alloys, batteries, and as a pigment."
color = "#5050FF"
value = 6

[ores.pr]
name = "Praseodymium"
description = "A soft, silvery, malleable metal, used in alloys, magnets, and as a coloring agent in glasses and enamels."
color = "#D8D8D8"
value = 7

[ores.gd]
name = "Gadolinium"
description = "A silvery-white, malleable, and ductile metal, used in various industrial and medical applications."
color = "#E6E6E6"
value = 8

[ores.sm]
name = "Samarium"
description = "A moderately hard silvery metal, used in magnets, lasers, and as a neutron absorber in nuclear reactors."
color = "#D4D4D4"
value = 9

[ores.yb]
name = "Ytterbium"
description = "A soft, malleable, and ductile metal, used in various alloys and as a doping agent in fiber optics."
color = "#C0C0C0"
value = 10

[ores.er]
name = "Erbium"
description = "A silvery-white metal, used in nuclear technology, metallurgy, and as a coloring agent in glasses and ceramics."
color = "#BEBEBE"
value = 11

[ores.dy]
name = "Dysprosium"
description = "A rare earth element with a metallic silver luster, used in magnets, lasers, and nuclear reactors."
color = "#C7C7C7"
value = 12

[ores.tb]
name = "Terbium"
description = "A silvery-white rare earth metal, used in solid-state devices, fuel cells, and as a dopant in materials."
color = "#D4D4D4"
value = 13

[ores.ho]
name = "Holmium"
description = "A relatively soft and malleable silvery-white metal, used in certain laser and magnetic applications."
color = "#D0D0D0"
value = 14

[ores.tm]
name = "Thulium"
description = "The least abundant of the naturally occurring rare earth elements, used in portable X-ray devices and lasers."
color = "#D4D4D4"
value = 15

[ores.lu]
name = "Lutetium"
description = "A hard, dense, silvery-white metal, used in various high-tech applications, including in cancer treatment."
color = "#E6E6E6"
value = 16

[ores.pt]
name = "Platinum"
description = "A dense, malleable, ductile, highly unreactive, precious, silverish-white transition metal."
color = "#E5E4E2"
value = 17

[ores.pd]
name = "Palladium"
description = "A rare and lustrous silvery-white metal used in electronics, jewelry, and catalytic converters."
color = "#E6E6E6"
value = 18

[ores.au]
name = "Gold"
description = "A dense, soft, malleable, and ductile metal with a bright yellow color and luster, traditionally used for coinage, jewelry, and other arts."
color = "#FFD700"
value = 19
