name = "Sol"
suns = 1

[planets]

[planets.mercury]
name = "Mercury"
texture = "rocky"
radius = 12.0
distance = 50
speed = 0.3
rotation = -0.1
color = [200, 75, 0] # brown
gravity = 0.1
initialAngle = 45

[planets.earth]
name = "Earth"
texture = "earthy"
radius = 40.0
distance = 160
speed = 0.2
rotation = -0.1
color = [0, 120, 255] # blue
gravity = 0.2
initialAngle = 180

[planets.earth.satellites]
[planets.earth.satellites.moon]
name = "Moon"
texture = "cratery"
radius = 8
speed = 0.2
rotation = 0.2
distance = 72
color = [255, 255, 255] # white

[planets.earth.products]
[planets.earth.products.gold]
name = "gold"
amount = 100
value = 1000

[planets.earth.products.silver]
name = "silver"
amount = 200
value = 500

[planets.earth.products.copper]
name = "copper"
amount = 300
value = 200

[planets.earth.products.iron]
name = "iron"
amount = 400
value = 100

[planets.mars]
name = "Mars"
texture = "rocky"
radius = 30.0
distance = 280
speed = 0.2
rotation = -0.1
color = [255, 150, 150] # sort of pinkish really
gravity = 0.3
initialAngle = 0

[planets.mars.satellites]
[planets.mars.satellites.phobos]
name = "Phobos"
texture = "cratery"
radius = 4
speed = 0.6
rotation = 0.2
distance = 50
color = [255, 192, 203] # pink

[planets.mars.satellites.deimos]
name = "Deimos"
texture = "cratery"
radius = 8
speed = -0.3
rotation = 0.2
distance = 60
color = [255, 192, 203] # pink

[planets.mars.products]
[planets.mars.products.lithium]
name = "lithium"
amount = 100
value = 1000

[planets.mars.products.uranium]
name = "uranium"
amount = 200
value = 500

[planets.mars.products.plutonium]
name = "plutonium"
amount = 300
value = 200

[planets.saturn]
name = "Saturn"
texture = "gassy"
radius = 45.0
distance = 500
speed = -0.1
rotation = 0
color = [255, 255, 0] # yellow
gravity = 0.1
hasrings = true
initialAngle = 130
